### ISSUE TITLE
Public IP URL Not Available

### ISSUE THREAD

**Issue by bah2830** [Mirantis/ceph-lcm#93] opened 2017-02-25 15:37 UTC
When getting the user-data for cloud-init it is trying to send a request to "http://169.254.169.254/latest/meta-data/public-ipv4" to get the public IP. This url is not responding and result in a looping error at boot.

In the majority of cases the nodes will not be publicly available so there wont be a public ip address anyways. There should be an option to skip this check when requesting the user-data.

The current workaround is to remove these lines from the resulting user-data file before using it with cloud-init

**Comment by 9seconds** [comment] 2017-02-27 12:41
Hi!

Could you please provide the boot log? There is the timeout in [peeking Decapod API](https://github.com/Mirantis/ceph-lcm/blob/master/decapodlib/decapodlib/cloud_config.py#L112) and in my test environment there is no metadata API at all therefore I cannot reproduce situation you are mentioning.

**Comment by 9seconds** [comment] 2017-03-13 07:13
I am closing this issue. Feel free to reopen if problem is still with us.

**Closed by 9seconds** 2017-03-13 07:13 UTC
